# Generated by Django 5.0.6 on 2024-05-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('GA', 'Gaming'), ('HA', 'Hardware'), ('PL', 'Platform'), ('PA', 'Playstation')], max_length=2),
        ),
    ]
